use std::path::PathBuf;
use tauri_plugin_sql::{Migration, MigrationKind};

/// Salt file backing the Stronghold argon2 password hash. Kept beside the app's
/// data so the encrypted vault is reproducible across launches on this device.
/// The salt is created by the plugin on first run if absent.
fn stronghold_salt_path() -> PathBuf {
    let mut dir = dirs_next::data_dir().unwrap_or_else(|| PathBuf::from("."));
    dir.push("lexica");
    std::fs::create_dir_all(&dir).ok();
    dir.push("stronghold.salt");
    dir
}

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    // Migrations are generated by Drizzle Kit into src-tauri/migrations and
    // embedded here; the SQL plugin applies them to the on-device SQLite DB.
    let migrations = vec![
        Migration {
            version: 1,
            description: "initial schema",
            sql: include_str!("../migrations/0000_simple_ravenous.sql"),
            kind: MigrationKind::Up,
        },
        Migration {
            version: 2,
            description: "pronunciations table",
            sql: include_str!("../migrations/0001_careless_sir_ram.sql"),
            kind: MigrationKind::Up,
        },
        Migration {
            version: 3,
            description: "tts cache table",
            sql: include_str!("../migrations/0002_blue_night_nurse.sql"),
            kind: MigrationKind::Up,
        },
        Migration {
            version: 4,
            description: "sync state table",
            sql: include_str!("../migrations/0003_normal_scarlet_spider.sql"),
            kind: MigrationKind::Up,
        },
    ];

    tauri::Builder::default()
        .setup(|app| {
            if cfg!(debug_assertions) {
                app.handle().plugin(
                    tauri_plugin_log::Builder::default()
                        .level(log::LevelFilter::Info)
                        .build(),
                )?;
            }
            Ok(())
        })
        .plugin(
            tauri_plugin_sql::Builder::default()
                .add_migrations("sqlite:lexica.db", migrations)
                .build(),
        )
        .plugin(tauri_plugin_dialog::init())
        .plugin(tauri_plugin_fs::init())
        // BYOK keys live in an OS-encrypted Stronghold vault, never in the
        // synced SQLite or the backup bundle (ADR-0006/0010). The vault is
        // unlocked from JS with an app-derived password; argon2 stretches it.
        .plugin(tauri_plugin_stronghold::Builder::with_argon2(&stronghold_salt_path()).build())
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}
